### ISSUE TITLE
proximity

### ISSUE THREAD

**Issue by Jordi-Valls** [emreg00/toolbox#2]
Hi Emre,

I cannot execute the code of proximity.... This code have to execute in python2, otherwise it do not work. However, after introduce the input toy.sif, and remove from toolbox (I execute the python script in same folder as wrapper), the script breaks giving me the following error;

GenRev not found, steiner wont work
Import error: Negex. Using keyword matching instead
DIAMOnD not found and thus will not be available!
Shrinking network to its LCC 11 15
Final shape: 11 15
Traceback (most recent call last):
  File "z_JV_proximity.py", line 6, in <module>
    d, z, (mean, sd) = wrappers.calculate_proximity(network, nodes_from, nodes_to, min_bin_size = 2)
  File "/home/jordi/multiscale_interactome/multiscale-interactome-master/proximity/toolbox-master/wrappers.py", line 552, in calculate_proximity
    bins = network_utilities.get_degree_binning(network, min_bin_size, lengths) # if lengths is given, it will only use those nodes
  File "/home/jordi/multiscale_interactome/multiscale-interactome-master/proximity/toolbox-master/network_utilities.py", line 1001, in get_degree_binning
    for node, degree in g.degree(): #.iteritems(): # iterator in networkx 2.0
ValueError: need more than 1 value to unpack

I tried to install GenRev, but there are problems to uncompress it, besides I would appreciate, a description of how to integrate this tool and negex in this toolbox,... And DIAMOnD also is not detected, I dont know which meaning is....
I suspect that I need other module or an older version of one module that I import.... Do you know where is the problem??

Thanks so much for your help

Jordi

**Comment by Jordi-Valls** [comment]
Solved... It was the networkx version, we need version 2.0, but I cannot obtain the same output as you, this is what I obtain...

GenRev not found, steiner wont work (here I miss two python scripts NWSteiner, kWalk they are not included in GenRev)
DIAMOnD not found and thus will not be available! (what is DIAMOnD I cannot included this module...)
Shrinking network to its LCC 11 15
Final shape: 11 15
(1.0, 1.3870748387117167, (0.671, 0.2371897974197035)) (It make sense? why are different from test?)

**Comment by Jordi-Valls** [comment]
Well finally I underestand... In the toolbox Readme the result is different in comparison with proximity folder.. I get the same results in proximity folder... So seems that it works!

**Comment by emreg00** [comment]
Hi Jordi,

Glad to hear that you were able to solve the issue. Let me know if you need additional clarification. You are right that the code is in python2 and requires networkx 2.+. The results being different is likely due to a change on the parameters (the default random seed used in the code had been changed when proximity repo was created and the README was not updated). The warning messages you have highlighted are for optional packages that are only required for certain specific analyzes. I will keep these points in mind for a potential clarification on the README, let me know if there is sth else. 

Thanks for your feedback!

Emre

**Comment by LCLWH** [comment]
Hi Emre,

I cannot execute the code of proximity either....I am sure that  the code is in python2 and  networkx is in 2.1 version (i also tried the networkx 2.2), but there is still the same error with Jordi, even the same error content .Do you know this problem?

Thanks so much for your help

LCLWH

**Comment by emreg00** [comment]
Hi LCLWH, it seems I have missed this -- are you still having this issue?
